---
title: "Stock_API"
author: "Nikki"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(rjson)
library(jsonlite)
library(RCurl)
library(lubridate)

stockmarket <- function(n, st_ex){
   
  # *****************************************************#
  # Function Description - 
  # This function facilitates the buy/sell of stocks as per the following rules:
  #   1. You are limited to 2 calls per minute, maximum 300 API calls per day.
  #   2. You must make at least 250 successful trades (buy/sell) per day.
  #   3. All trading is to be done between 10am-4pm.
  #   
  # Input -
  #   n : Number of API calls to do. (Maximum allowed is 300)
  #   st_ex : List of stock symbols 
  # 
  # Output -
  #   This will check through all the conditions mentioned and buy/sell stocks alternatively for the list of stock symbols.
  # 
  # *****************************************************#
    
  if ((hour(now()) >= 10) & ((hour(now()) <= 15))){
    print("Welcome to Stock Marketing for the day!")
    calls_perday_limit <- n
    print("Your maximum API call limit - 300/day")
    
    stock_exc <- st_ex   
    # Continue to do buy/sell in stock market untill it exceeds the maximum API limit or untill it gets 16:00:00 hours
    
	print(paste("API Calls pending - ",calls_perday_limit ))
	
	# Alternate the buy and sell of stocks
	# Buy initial stocks
	bs <- 1
	while((bs <= length(stock_exc)) & (calls_perday_limit != 1) & (hour(now()) <= 15)){
	  buy_url <- paste("https://projectrex.net/stocks/?key=3908807a &av_key=WAXKUU383HFZU74Y&request=buy&symbol=",stock_exc[bs],"&quantity=2", sep = "")
	  buy_link <- URLencode(buy_url)
	  buy_stock <- getURL(buy_link)
	  print(buy_stock)
	  calls_perday_limit <- calls_perday_limit - 1
	  Sys.sleep(30)
	  bs <- bs + 1
	}   
	
	# Sell all the initial stocks brought during the beginning of process 
	ss <- 1
	while((ss <= length(stock_exc)) & (calls_perday_limit != 1) & (hour(now()) <= 15)){
		sell_url <- paste("https://projectrex.net/stocks/?key=3908807a &av_key=WAXKUU383HFZU74Y&request=sell&symbol=",stock_exc[ss],"&quantity=2", sep = "")
		sell_link <- URLencode(sell_url)
		sell_stock <- getURL(sell_link)
		print(sell_stock)
		calls_perday_limit <- calls_perday_limit - 1
		Sys.sleep(30)
		ss <- ss + 1
	}
	if(calls_perday_limit == 1){
		print("Sorry! Exceeded the maximum limit of API call for a day")
		}else{
		print("Thank You!")
		}
		
	log_check <- readline(prompt="Do you want to print logs (Y/N): ")
	if(log_check == "Y"){
		print("Printing you the logs!!")
		log_link <- URLencode("https://projectrex.net/stocks/?key=3908807a &av_key=WAXKUU383HFZU74Y&request=log")
		logs <- getURL(log_link)
		fileConn<-file("logs.txt")
		writeLines(logs, fileConn)
		close(fileConn)
		print("The logs are available in logs.txt file.")
	}else{
		print("Thank You!")
	}
    }
  else{
    profile_link <- URLencode("https://projectrex.net/stocks/?key=3908807a &av_key=WAXKUU383HFZU74Y&request=profile")
    prof <- getURL(profile_link)
    print(prof)
    print("Sorry! Stock Market is closed right now.Please trying running the script between 10:00:00 to 16:00:00")
  }
}

# ***************************************************** #

# Call the function passing the parameters
stockmarket(300, c("INTC","IBM","MSFT","CSCO"))


```

